# Generated by Django 4.1.7 on 2023-04-23 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("social_media", "0002_post_author_post_likes_profile_follow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follow",
            options={"verbose_name_plural": "follow"},
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name_plural": "profile"},
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("follower", "followed")},
        ),
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "posts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="hashtags",
                        to="social_media.post",
                    ),
                ),
            ],
        ),
    ]
