# Generated by Django 4.1.7 on 2023-04-23 23:01

from django.db import migrations, models
import social_media.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "social_media",
            "0003_alter_follow_options_alter_profile_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="photo_image",
            field=models.ImageField(
                null=True,
                upload_to=social_media.models.profile_image_file_path,
            ),
        ),
    ]
