# Generated by Django 4.1.7 on 2023-04-24 02:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "social_media",
            "0005_userprofile_remove_profile_user_remove_hashtag_posts_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={"ordering": ["-id"], "verbose_name_plural": "profile"},
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="followers",
            field=models.ManyToManyField(
                related_name="followers",
                related_query_name="followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="following",
            field=models.ManyToManyField(
                related_name="user_follows",
                related_query_name="following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
