# Generated by Django 4.1.7 on 2023-04-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0006_alter_userprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="username",
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
